---
# group_vars/dbservers/main.yml

mysql_root_password: "{{ vault_db_root_password }}"
mysql_bind_address:  "0.0.0.0"

mysql_databases:
  - name: "{{ laravel_repo_name }}"

mysql_users:
  - name: "{{ laravel_repo_name }}"
    password: "{{ vault_db_password }}"
    priv: "{{ laravel_repo_name }}.*:ALL"
    host: "%"